In [2]:
suppressMessages({library("rwwa"); library(quantreg)})

gmst <- read.table("data/gmst.dat", col.names = c("year", "gmst"))
gmst$gmst <- gmst$gmst - gmst$gmst[gmst$year == 2026]

## Check data availability

In [3]:
t((sapply(list.files("stations", full.names = T), function(fnm) {
    ts <- read.csv(fnm)[,1:2]
    c("prop_missing" = sum(is.na(ts)) / nrow(ts) * 100,
      "nobs" = nrow(ts) / 365)
    })))

                                                                     prop_missing
stations/A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv                8.9395090
stations/A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                        4.9088198
stations/BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv        0.4588748
stations/CADIZ_SP_LAT36.5008_LON-6.2567.csv                           2.7528861
stations/CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                     5.3748512
stations/CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv              2.0672047
stations/GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv              2.4100092
stations/GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                  0.0000000
stations/HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv             4.7385837
stations/JAEN_SP_LAT37.7778_LON-3.8075.csv                            1.6807871
stations/JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv            6.4904698
stations/KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                  6.5900259
stations/LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                      8.7959089
stations/MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv               0.9527564
stations/MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           22.8614760
stations/OURENSE_SP_LAT42.3278_LON-7.8603.csv                         6.5285864
stations/PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                        6.6158730
stations/PORTO_SP_LAT41.1331_LON-8.6.csv                              1.0892912
stations/ROTA_SP_LAT36.6389_LON-6.3317.csv                            6.4530290
stations/SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv  5.6965407
stations/SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv               5.4868681
stations/TARIFA_SP_LAT36.0153_LON-5.5975.csv                          8.6521525
stations/VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                   3.0629205
                                                                     nobs
stations/A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv                54.12329
stations/A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                        47.77534
stations/BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv        71.04932
stations/CADIZ_SP_LAT36.5008_LON-6.2567.csv                           33.93699
stations/CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                     27.62740
stations/CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv              33.26575
stations/GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv              26.71507
stations/GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                  24.70959
stations/HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv             20.69863
stations/JAEN_SP_LAT37.7778_LON-3.8075.csv                            20.04932
stations/JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv            38.66575
stations/KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                  16.92055
stations/LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                      29.46575
stations/MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv               41.69589
stations/MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           139.09863
stations/OURENSE_SP_LAT42.3278_LON-7.8603.csv                         28.70411
stations/PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                        21.57534
stations/PORTO_SP_LAT41.1331_LON-8.6.csv                              35.71507
stations/ROTA_SP_LAT36.6389_LON-6.3317.csv                            18.72329
stations/SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv  41.02466
stations/SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv               37.44932
stations/TARIFA_SP_LAT36.0153_LON-5.5975.csv                          38.88493
stations/VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                   34.61644

In [61]:
for (fnm in list.files("stations", full.names = T)) {
    df <- read.csv(fnm, col.names = c("date", "pr"))
    df <- df[!is.na(df$pr),]
    
    stn <- strsplit(fnm, "/|_SP")[[1]][2]
    if (as.numeric(strsplit(fnm, "LAT|_LON")[[1]][2]) > 39.5) { rnm <- "n" } else { rnm <- "s" }
    
    df$year <- as.integer(substr(df$date,1,4))
    df$month <- as.integer(substr(df$date,6,7))
    
    df <- merge(gmst, df)
    
    qq <- quantile(df[(df$year >= 1990) & (df$year <= 2020), "pr"], c(0.95, .99, .995, .99725, .9975, .999))
    
    # get abs values of extremes
    df_x <- df[df[,"pr"] >= qq["99%"],]
    
    # decluster using built-in method
    df_dc <- decluster(df[,"pr"], threshold = qq["99%"], r = 1)
    
    n_peryear <- aggregate(df[,"pr"] >= qq["99%"], by = list("year" = df$year), FUN = "sum", simplify = T)
    n_perymonth <- aggregate(df[,"pr"] >= qq["99%"], by = list(df$month, df$year), FUN = "sum", simplify = T)
    n_permonth <- aggregate(n_perymonth[,"x",drop = F], by = list("cmonth" = n_perymonth$Group.1), FUN = "mean")
    n_permonth$m_offset <- ((n_permonth$cmonth + 4) %% 12) + 1 # adjust months to cut at start of August (driest part of year)
    
    png(paste0("stn-fig/q-exceedances_",rnm,"_",stn,".png"), h = png_res, w = png_res * 3); {
        prep_window(c(1,3), oma = c(0,0,2,0))
    
        plot(df_x$year, df_x[,"pr"], main = "Magnitude of exceedances")
        lines(df_x$year, fitted(loess(pr ~ year, df_x)), col = "forestgreen", lty = "22", lwd = 3) # add a smoother through magnitude of exceedances
        lines(df_x$year, fitted(lm(pr ~ gmst, df_x)), lwd = 3, col = "darkblue")
        
        
        plot(n_peryear, main = "Number of exceedances per year", xlab = "Year")
        lines(n_peryear$year, fitted(loess(x ~ year, n_peryear)), col = "forestgreen", lty = "22", lwd = 3) # add a smoother through number of exceedances
        lines(n_peryear$year, fitted(loess(x ~ year, n_peryear)), col = "forestgreen", lty = "22", lwd = 3) # add a smoother through number of exceedances
        lines(n_peryear$year, fitted(lm(x ~ gmst, merge(gmst, n_peryear))), lwd = 3, col = "darkblue")
        
        mtext(paste0(stn, " (",rnm, ")"), outer = T, side = 3)
        
        # check that we're capturing all the exceedances
        plot(n_permonth$cmonth, n_permonth$x, main = "Mean exceedances per calendar month", xlim = c(1,12), xlab = "Calendar month", type = "o")
    }; dev.off()
}

## Quick trend fitting

In [31]:
cov_2026 <- gmst[gmst$year == 2026,,drop = F]
cov_cf <- cov_2026 - 1.3

stn_res <- data.frame(t(sapply(list.files("ts-stn", pattern = "rx1day-ondjfm", full.names = T), function(fnm) {
    stn <- strsplit(fnm, "ondjfm_|_SP")[[1]][2]
    lat <- as.numeric(strsplit(fnm, "LAT|_LON")[[1]][2])
    lon <- as.numeric(strsplit(fnm, "LON|.csv")[[1]][2])
    if (lat > 39.5) { rnm <- "n" } else { rnm <- "s" }
    df <- merge(gmst, read.csv(fnm, col.names = c("year", "pr")))
    mdl <- fit_ns("gev", "fixeddisp", df, covnm = "gmst", varnm = "pr", lower = F)
    c(stn = stn, rnm = rnm, lon = lon, lat = lat, mdl_ests(mdl, cov_f = cov_2026, cov_cf = cov_cf), nobs = nrow(df))
})))
write.csv(stn_res, "stn-res_no-bootstrap.csv")

In [17]:
stn_res[order(stn_res$lat),]

                                                                                 stn
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 KENITRA_PORT_LYAUTEY
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         TARIFA
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          CADIZ
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           ROTA
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              MALAGA_AEROPUERTO
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           JEREZ_DE_LA_FRONTERA
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 GRAZALEMA
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           MORON_DE_LA_FRONTERA
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             GRANADA_AEROPUERTO
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            HUELVA_RONDA_DEL_ESTE
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              SEVILLA_SAN_PABLO
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           JAEN
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             CORDOBA_AEROPUERTO
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       BADAJOZ_TALAVERA_LA_REAL
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    CIUDAD_REAL
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             PORTO
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  VIGO_PEINADOR
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        OURENSE
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       PONTEVEDRA
ts-stn/rx1day-ondjfm_SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv SANTIAGO_DE_COMPOSTELA_LABACOL
ts-stn/rx1day-ondjfm_LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                     LUGO_ROZAS
ts-stn/rx1day-ondjfm_A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv               A_CORUNA_ALVEDRO
ts-stn/rx1day-ondjfm_A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                       A_CORUNA
                                                                                 rnm
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 s
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         s
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          s
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           s
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              s
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           s
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 s
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           s
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             s
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            s
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              s
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           s
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             s
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       s
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    s
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             n
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  n
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        n
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       n
ts-stn/rx1day-ondjfm_SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv n
ts-stn/rx1day-ondjfm_LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                     n
ts-stn/rx1day-ondjfm_A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv               n
ts-stn/rx1day-ondjfm_A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                       n
                                                                                 lon
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 -6.6
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         -5.5975
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          -6.2567
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           -6.3317
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              -4.4881
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           -6.0556
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 -5.366074
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           -5.6156
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             -3.7892
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            -6.9094
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              -5.8792
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           -3.8075
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             -4.8458
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       -6.8292
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    -3.9194
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             -8.6
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  -8.6239
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        -7.8603
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       -8.6164
ts-stn/rx1day-ondjfm_SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv -8.4106
ts-stn/rx1day-ondjfm_LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                     -7.4558
ts-stn/rx1day-ondjfm_A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv               -8.3719
ts-stn/rx1day-ondjfm_A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                       -8.4192
                                                                                 lat
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 34.3
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         36.0153
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          36.5008
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           36.6389
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              36.6667
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           36.7506
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 36.7583892
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           37.1581
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             37.1894
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            37.28
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              37.4167
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           37.7778
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             37.8442
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       38.8831
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    38.9892
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             41.1331
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  42.2392
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        42.3278
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       42.44
ts-stn/rx1day-ondjfm_SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv 42.8878
ts-stn/rx1day-ondjfm_LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                     43.1153
ts-stn/rx1day-ondjfm_A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv               43.3067
ts-stn/rx1day-ondjfm_A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                       43.3669
                                                                                 mu0
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 47.0929764314773
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         46.5116535741147
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          36.2386825538179
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           42.8978491416727
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              47.1914453840205
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           46.9255388354736
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 135.073388189809
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           37.8576864860279
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             32.1860139288473
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            33.2442151755222
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              32.8608515644952
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           28.5725303813447
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             36.4071525127297
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       23.7782582292212
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    27.3235263091234
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             53.380734340339
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  69.6923295713994
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        28.3177192973666
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       78.7377277954962
ts-stn/rx1day-ondjfm_SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv 79.4779321242724
ts-stn/rx1day-ondjfm_LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                     49.1595453191672
ts-stn/rx1day-ondjfm_A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv               27.6699850549753
ts-stn/rx1day-ondjfm_A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                       44.7200071393776
                                                                                 sigma0
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 17.1923383497546
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         18.0152021952749
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          13.022181122828
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           13.1676758141782
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              19.1422434333426
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           14.5478809357242
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 43.1845556301978
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           13.4936137040928
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             9.92007738812281
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            11.6760326222254
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              9.94989852704208
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           9.62058181156997
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             13.7682302482592
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       7.04506359071423
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    7.70764968004412
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             15.7114104995368
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  17.6469607933832
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        7.64173859286555
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       19.9749524430626
ts-stn/rx1day-ondjfm_SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv 19.9412951306382
ts-stn/rx1day-ondjfm_LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                     13.1749085789085
ts-stn/rx1day-ondjfm_A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv               7.34601287135889
ts-stn/rx1day-ondjfm_A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                       14.9903670057454
                                                                                 alpha_gmst
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 5.25171776126108
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         -8.03908272203567
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          -10.7169677575569
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           -2.84834343206233
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              -4.43948254102058
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           2.83288487754525
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 16.1618476112845
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           -3.36864620060067
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             9.30539661196368
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            -5.32988477192374
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              -8.07389815975962
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           -7.39690616760557
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             -1.80524080782619
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       -3.76171901890898
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    3.82052733919378
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             3.65719087368316
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  0.392608246096521
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        -9.60376939431529
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       23.9950439676205
ts-stn/rx1day-ondjfm_SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv 15.7089583176987
ts-stn/rx1day-ondjfm_LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                     11.7017198968288
ts-stn/rx1day-ondjfm_A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv               -10.7692930311044
ts-stn/rx1day-ondjfm_A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                       11.1575171887649
                                                                                 shape
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 0.0397303693965906
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         -0.0134165954684124
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          -0.0705574344638449
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           0.269939344543148
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              0.0870859167505965
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           0.0476467054723274
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 -0.0283733969751991
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           0.0804211209461336
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             -0.0201795450809476
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            0.362499538633375
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              0.135412927998074
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           -0.109407053452337
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             0.172473651765371
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       0.203786798324445
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    0.190741961680377
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             -0.127909372073335
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  0.129627657974499
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        -0.164661572178495
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       -0.298839876474803
ts-stn/rx1day-ondjfm_SANTIAGO_DE_COMPOSTELA_LABACOL_SP_LAT42.8878_LON-8.4106.csv 0.177500695258153
ts-stn/rx1day-ondjfm_LUGO_ROZAS_SP_LAT43.1153_LON-7.4558.csv                     -0.210930018613831
ts-stn/rx1day-ondjfm_A_CORUNA_ALVEDRO_SP_LAT43.3067_LON-8.3719.csv               0.193777880244304
ts-stn/rx1day-ondjfm_A_CORUNA_SP_LAT43.3669_LON-8.4192.csv                       0.122690254428698
                                                                                 disp
ts-stn/rx1day-ondjfm_KENITRA_PORT_LYAUTEY_SP_LAT34.3_LON-6.6.csv                 0.365072239058203
ts-stn/rx1day-ondjfm_TARIFA_SP_LAT36.0153_LON-5.5975.csv                         0.387326633454738
ts-stn/rx1day-ondjfm_CADIZ_SP_LAT36.5008_LON-6.2567.csv                          0.359344772081293
ts-stn/rx1day-ondjfm_ROTA_SP_LAT36.6389_LON-6.3317.csv                           0.306954219795291
ts-stn/rx1day-ondjfm_MALAGA_AEROPUERTO_SP_LAT36.6667_LON-4.4881.csv              0.405629521994348
ts-stn/rx1day-ondjfm_JEREZ_DE_LA_FRONTERA_SP_LAT36.7506_LON-6.0556.csv           0.310020540983679
ts-stn/rx1day-ondjfm_GRAZALEMA_SP_LAT36.7583892_LON-5.366074.csv                 0.319711796742032
ts-stn/rx1day-ondjfm_MORON_DE_LA_FRONTERA_SP_LAT37.1581_LON-5.6156.csv           0.356429960638849
ts-stn/rx1day-ondjfm_GRANADA_AEROPUERTO_SP_LAT37.1894_LON-3.7892.csv             0.308210808895219
ts-stn/rx1day-ondjfm_HUELVA_RONDA_DEL_ESTE_SP_LAT37.28_LON-6.9094.csv            0.351219980997552
ts-stn/rx1day-ondjfm_SEVILLA_SAN_PABLO_SP_LAT37.4167_LON-5.8792.csv              0.302788821753863
ts-stn/rx1day-ondjfm_JAEN_SP_LAT37.7778_LON-3.8075.csv                           0.33670737884144
ts-stn/rx1day-ondjfm_CORDOBA_AEROPUERTO_SP_LAT37.8442_LON-4.8458.csv             0.378173773503576
ts-stn/rx1day-ondjfm_BADAJOZ_TALAVERA_LA_REAL_SP_LAT38.8831_LON-6.8292.csv       0.296281734465164
ts-stn/rx1day-ondjfm_CIUDAD_REAL_SP_LAT38.9892_LON-3.9194.csv                    0.282088394918138
ts-stn/rx1day-ondjfm_PORTO_SP_LAT41.1331_LON-8.6.csv                             0.294327357869708
ts-stn/rx1day-ondjfm_VIGO_PEINADOR_SP_LAT42.2392_LON-8.6239.csv                  0.253212382222121
ts-stn/rx1day-ondjfm_OURENSE_SP_LAT42.3278_LON-7.8603.csv                        0.269857134772015
ts-stn/rx1day-ondjfm_PONTEVEDRA_SP_LAT42.44_LON-8.6164.csv                       0.253689724130001

### And now, with NAO

In [32]:
# load covariate data
gmst = read.table("ts-obs/gmst.dat", col.names = c("year", "gmst"))
gmst$gmst <- gmst$gmst - gmst$gmst[gmst$year == 2026]

nao <- load_ts("ts-obs/med-storms_nao-djf_era5-stn.dat", col.names = c("year", "nao"))
cov_df <- merge(gmst, nao)

# define factual & counterfactual climates
cov_f <- cov_df[cov_df$year == 2026,c(-1),drop = F]
cov_cf <- rbind("pi" = cov_f - c(1.3,0),
                "naoneutral" = c(cov_f$gmst, 0),
                "pineutral" = c(-1.3, 0))


stn_res <- data.frame(t(sapply(list.files("ts-stn", pattern = "rx1day-ondjfm", full.names = T), function(fnm) {
    stn <- strsplit(fnm, "ondjfm_|_SP")[[1]][2]
    lat <- as.numeric(strsplit(fnm, "LAT|_LON")[[1]][2])
    lon <- as.numeric(strsplit(fnm, "LON|.csv")[[1]][2])
    if (lat > 39.5) { rnm <- "n" } else { rnm <- "s" }
    df <- merge(cov_df, read.csv(fnm, col.names = c("year", "pr")))
    mdl <- fit_ns("gev", "fixeddisp", df, covnm = c("nao", "gmst"), varnm = "pr", lower = F)
    c(stn = stn, rnm = rnm, lon = lon, lat = lat, mdl_ests(mdl, cov_f = cov_f, cov_cf = cov_cf), nobs = nrow(df))
})))

write.csv(stn_res, "stn-res_with-nao_no-bootstrap.csv")

# Table of stations

In [36]:
stn_res <- read.csv("stn-res_with-nao_no-bootstrap.csv")
stn_res <- stn_res[order(stn_res$rnm),]
stn_res <- stn_res[stn_res$nobs >= 20,]

In [39]:
stn_res <- stn_res[,c("rnm", "stn", "lon", "lat", "dI_rel_pi", "nobs")]

In [40]:
data.frame(stn_res$rnm, stn_res$stn, apply(round(stn_res[,c("lon", "lat")], 2), 1, paste0, collapse = ", "), round(stn_res$dI_rel, 2), stn_res$nobs)

   stn_res.rnm stn_res.stn
1  n           A_CORUNA_ALVEDRO
2  n           A_CORUNA
13 n           LUGO_ROZAS
17 n           PONTEVEDRA
18 n           PORTO
20 n           SANTIAGO_DE_COMPOSTELA_LABACOL
23 n           VIGO_PEINADOR
3  s           BADAJOZ_TALAVERA_LA_REAL
4  s           CADIZ
5  s           CIUDAD_REAL
6  s           CORDOBA_AEROPUERTO
7  s           GRANADA_AEROPUERTO
8  s           GRAZALEMA
9  s           HUELVA_RONDA_DEL_ESTE
10 s           JAEN
11 s           JEREZ_DE_LA_FRONTERA
14 s           MALAGA_AEROPUERTO
15 s           MORON_DE_LA_FRONTERA
21 s           SEVILLA_SAN_PABLO
22 s           TARIFA
   apply.round.stn_res...c..lon....lat.....2...1..paste0..collapse........
1  -8.37, 43.31
2  -8.42, 43.37
13 -7.46, 43.12
17 -8.62, 42.44
18 -8.6, 41.13
20 -8.41, 42.89
23 -8.62, 42.24
3  -6.83, 38.88
4  -6.26, 36.5
5  -3.92, 38.99
6  -4.85, 37.84
7  -3.79, 37.19
8  -5.37, 36.76
9  -6.91, 37.28
10 -3.81, 37.78
11 -6.06, 36.75
14 -4.49, 36.67
15 -5.62, 37.16
21 -5.88, 37.42
22 -5.6, 36.02
   round.stn_res.dI_rel..2. stn_res.nobs
1  -34.18                   25
2   18.23                   38
13  36.96                   26
17  49.24                   37
18  12.63                   61
20  43.60                   33
23  10.35                   52
3  -13.09                   68
4  -26.48                   51
5   17.63                   25
6    7.26                   60
7   50.24                   51
8   11.25                   20
9   -9.12                   29
10 -29.15                   36
11  62.69                   30
14   1.50                   71
15  -3.16                   66
21 -27.25                   40
22  -5.97                   30

             1              2             12             15             16
"-8.37, 43.31" "-8.42, 43.37" "-7.46, 43.12" "-8.62, 42.44"  "-8.6, 41.13"
            17             20              3              4              5
"-8.41, 42.89" "-8.62, 42.24" "-6.83, 38.88"  "-6.26, 36.5" "-3.92, 38.99"
             6              7              8              9             10
"-4.85, 37.84" "-3.79, 37.19" "-5.37, 36.76" "-6.91, 37.28" "-3.81, 37.78"
            11             13             14             18             19
"-6.06, 36.75" "-4.49, 36.67" "-5.62, 37.16" "-5.88, 37.42"  "-5.6, 36.02"